name: ğŸš€ Deploy & Purge Cache

# mainãƒ–ãƒ©ãƒ³ãƒã¸ã®pushã‚’æ¤œçŸ¥
on:
  push:
    branches: [ "main" ]

  # Actions ã‚¿ãƒ–ã‹ã‚‰æ‰‹å‹•ã§å®Ÿè¡Œã§ãã‚‹ã‚ˆã†ã«ã™ã‚‹
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: ['18.x']
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      # ãƒ‘ãƒƒã‚±ãƒ¼ã‚¸ã®ã‚¤ãƒ³ã‚¹ãƒˆãƒ¼ãƒ«ã¨ã‚¢ãƒ—ãƒªã®ãƒ“ãƒ«ãƒ‰
      - name: ğŸ›  Install and Build
        run: |
          yarn install --frozen-lockfile
          yarn run build
        env:
          CI: true
          
      # GitHub Pages ã«ãƒ‡ãƒ—ãƒ­ã‚¤
      - name: ğŸš€ Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./build
          cname: bingo.frogapp.net
          
  purge-cache:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      # Cloudflare ã®ã‚­ãƒ£ãƒƒã‚·ãƒ¥ã‚’å‰Šé™¤
      - name: ğŸ—‘ Purge Cache
        env: 
          ZONE_ID: ${{ secrets.ZONE_ID }}
          GLOBAL_API_KEY: ${{ secrets.GLOBAL_API_KEY }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}        
        run: |
          curl -X DELETE "https://api.cloudflare.com/client/v4/zones/${ZONE_ID}/purge_cache" \
          -H "X-Auth-Email: ${EMAIL_ADDRESS}" \
          -H "X-Auth-Key: ${GLOBAL_API_KEY}" \
          -H "Content-Type: application/json" \
          --data '{"purge_everything":true}'
